
services:
  loglyapi:
    build: .
    ports:
      - "5000:5000"
    command: uvicorn app:app --host 0.0.0.0 --port 5000 --reload
    develop:
      watch:
      - action: sync
        path: ./app
        target: /code/app
  loglyweb:
    build: ./web
    ports:
      - "5173:5173"
    command: npm run dev
    develop:
      watch:
      - action: sync
        path: ./web
        target: /web
