name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: ./web
        run: npm ci

      - name: Build project
        working-directory: ./web
        run: npm run build

      - name: Cypress component tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./web
          command: npx cypress run --component